#!/usr/bin/env python3
"""Every tier-level number of the thesis, from the measurements: the tables of energy_tests.md §3, §4, §7, §8.3.

ROLE IN THE PIPELINE
    measure/ -> energy/three_tier.py -> analyze/tier_energy.py -> results/tier_energy.md

    No simulation here: this is what the measurements say on their own. What an
    OLT query costs at each batch size, at each energy boundary; from which batch
    the OLT is cheaper than the ONU or the phone; what one more query adds to a busy
    OLT; how accurate each tier is and whether its confidence tells right from
    wrong answers.

TABLES WRITTEN
    1. OLT batch curve (§3.2)       energy per token and per query, batch 1..64, the reference sweep
    2. Replication (§3.2)           every sweep side by side, decode energy per token
    3. Tier prices (§3.3, §8.5)     phone and ONU J per query, average and marginal
    4. OLT per query (§3.3)         at the tiers' real answer lengths, four boundaries
    5. Crossovers (§3.3, §7)        batch from which the OLT beats the ONU and the phone
    6. Marginal cost (§8.3)         what one query adds, idle OLT and busy OLT
    7. Answers (§4)                 accuracy, confidence, lengths, truncation, Welch t

INPUTS
    results/measurements/ (OLT sweeps, answers) and config/energy_sources.yaml,
    all through energy/three_tier.py.

Usage:
    python src/analyze/tier_energy.py        # prints the tables, writes results/tier_energy.md (~5 s)
"""
from __future__ import annotations

import math
import statistics as st
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))       # implementation/src
from energy.three_tier import (OLT_REFERENCE, ROOT, TIERS, OltCurve, boundary, load_answers,  # noqa: E402
                               olt_factor, olt_reference, olt_runs, published_rates)

OUT = ROOT / "results" / "tier_energy.md"


def welch_t(a: list[float], b: list[float]) -> float:
    """Welch's t for mean(a) - mean(b): how clearly two groups' means differ. NaN if a group is tiny."""
    if len(a) < 2 or len(b) < 2:
        return float("nan")
    den = math.sqrt(st.variance(a) / len(a) + st.variance(b) / len(b))
    return (st.mean(a) - st.mean(b)) / den if den else float("nan")


def crossing(xs: list[float], ys: list[float], target: float) -> float | None:
    """First x at which the falling curve ys drops below target, interpolated log-log.

    Used for "from which batch size is the OLT cheaper than tier X". None when the
    curve never gets there within the measured batches (1..64).
    """
    for (x0, y0), (x1, y1) in zip(zip(xs, ys), zip(xs[1:], ys[1:])):
        if y0 >= target > y1:
            f = (math.log(y0) - math.log(target)) / (math.log(y0) - math.log(y1))
            return math.exp(math.log(x0) + f * (math.log(x1) - math.log(x0)))
    return None


def table(headers: list[str], rows: list[list]) -> list[str]:
    """A markdown table, as a list of lines."""
    return (["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
            + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows])


def fmt_batch(x: float | None) -> str:
    """A crossover batch for the table: '≈ 5.2', or 'not within 64'."""
    return f"≈ {x:.1f}" if x else "not within 64"


def main() -> int:
    """Compute every table from the measurements and write results/tier_energy.md."""
    runs, ref_run = olt_runs(), olt_reference()       # the reference sweep prices everything
    ref_rows = ref_run["batch_curve"]
    recs, models, sources = load_answers()
    B = [r["batch"] for r in ref_rows]
    bnd = boundary()
    k_sys, k_low = olt_factor("system"), olt_factor("system-low")
    k_marg = olt_factor("system", "marginal")

    # mean prompt and generated tokens of each tier's real answers (§4)
    tok = {t: (st.mean(r["tp"] for r in recs[t]), st.mean(r["tg"] for r in recs[t])) for t in TIERS}
    price = {acc: {t: rates[t]["pf"] * tok[t][0] + rates[t]["dec"] * tok[t][1] for t in ("user", "onu")}
             for acc, rates in (("average", published_rates("average")), ("marginal", published_rates("marginal")))}

    # OLT J per query at its own real answer lengths, at each boundary
    pin, gout = tok["olt"]
    olt_gpu = [r["prefill_J_per_input_token"] * pin + r["decode_J_per_output_token"] * gout for r in ref_rows]
    olt_net = [r["prefill_J_per_input_token_net"] * pin + r["decode_J_per_output_token_net"] * gout for r in ref_rows]
    olt_sys = [g * k_sys for g in olt_gpu]
    olt_low = [g * k_low for g in olt_gpu]

    L = ["# Tier energy — tables from the measurements", "",
         "Generated by `src/analyze/tier_energy.py`. Answers: " + ", ".join(sources) + ". "
         f"OLT: {ref_run['model']} ({ref_run['precision']}) on one {ref_run['gpu']}, idle {ref_run['idle_power_W']} W.", ""]

    L += [f"## 1. OLT batch curve ({OLT_REFERENCE}, the reference sweep, GPU card)", "",
          f"Per query = {ref_rows[0]['input_tokens'] // ref_rows[0]['batch']} prompt and "
          f"{ref_run['output_tokens_per_sequence']} generated tokens, as in the sweep. Marginal = the batch energy's "
          "slope between adjacent batch sizes. Decode spread = min–max over the repeats.", ""]
    L += table(["Batch", "Prefill J/in-tok (net)", "Decode J/out-tok [spread]", "Tokens/s", "Power W",
                "Avg J/query", "Marginal J/query"],
               [[r["batch"], f"{r['prefill_J_per_input_token']:.4f} ({r['prefill_J_per_input_token_net']:.4f})",
                 f"{r['decode_J_per_output_token']:.3f} [{min(r['trials_decode_J_per_output_token']):.3f}–"
                 f"{max(r['trials_decode_J_per_output_token']):.3f}]",
                 f"{r['tokens_per_s']:,.0f}", f"{r['mean_power_W']:.1f}",
                 f"{r['average_J_per_query']:.0f}", f"{r['marginal_J_per_query']:.1f}"] for r in ref_rows])
    swing = ref_rows[0]["decode_J_per_output_token"] / ref_rows[-1]["decode_J_per_output_token"]
    L += ["", f"Decode energy per token falls {swing:.0f}× from batch {B[0]} to {B[-1]}.", ""]

    # every sweep's decode J per output token, at every batch size any of them measured
    dec = {name: {r["batch"]: r["decode_J_per_output_token"] for r in rep["batch_curve"]} for name, rep in runs.items()}
    ref = dec[OLT_REFERENCE]
    others = [n for n in runs if n != OLT_REFERENCE]
    diffs = [d[b] / ref[b] - 1 for n in others for d in [dec[n]] for b in d if b in ref]
    L += ["## 2. Replication: every sweep, decode J per output token", "",
          f"Each run is an independent container on a rented L4. Difference = against {OLT_REFERENCE}, "
          "at the batch sizes both measured.", ""]
    L += table(["Batch"] + list(runs) + [f"vs {OLT_REFERENCE}"],
               [[b] + [f"{dec[n][b]:.4f}" if b in dec[n] else "–" for n in runs]
                + [", ".join(f"{n} {dec[n][b] / ref[b] - 1:+.1%}" for n in others if b in dec[n] and b in ref) or "–"]
                for b in sorted({b for d in dec.values() for b in d})])
    L += ["", f"Largest difference from {OLT_REFERENCE}: {max(abs(d) for d in diffs):.1%}." if diffs else "", ""]

    L += ["## 3. Phone and ONU per query", "",
          "At each tier's mean real answer length. Marginal accounting charges no tier for being on: "
          "the ONU loses its board's idle draw; the phone is unchanged.", ""]
    L += table(["Tier", "Prompt tokens", "Generated tokens", "J/query, average", "J/query, marginal"],
               [[t, f"{tok[t][0]:.1f}", f"{tok[t][1]:.1f}", f"{price['average'][t]:.1f}",
                 f"{price['marginal'][t]:.1f}"] for t in ("user", "onu")])
    L += [""]

    L += ["## 4. OLT per query, at its real answer length", "",
          f"{pin:.0f} prompt and {gout:.0f} generated tokens. Whole system = GPU card × "
          f"{bnd['it_over_accel']:.2f} (host and idle machines, Google's shares) × PUE: "
          f"× {k_sys:.2f} at PUE {bnd['pue_isp']}, × {k_low:.2f} at PUE {bnd['pue_low']}.", ""]
    L += table(["Batch", "GPU card", "GPU, net of idle", f"Whole system, PUE {bnd['pue_isp']}",
                f"Whole system, PUE {bnd['pue_low']}"],
               [[b, f"{g:.1f}", f"{n:.1f}", f"**{s:.1f}**", f"{lo:.1f}"]
                for b, g, n, s, lo in zip(B, olt_gpu, olt_net, olt_sys, olt_low)])
    L += [""]

    L += ["## 5. Batch size from which the OLT is cheaper per query", ""]
    L += table(["Lower tier", "Its J/query", f"Whole system, PUE {bnd['pue_isp']}",
                f"Whole system, PUE {bnd['pue_low']}", "GPU card only", "GPU, net of idle"],
               [[t, f"{price['average'][t]:.1f}", fmt_batch(crossing(B, olt_sys, price['average'][t])),
                 fmt_batch(crossing(B, olt_low, price['average'][t])),
                 fmt_batch(crossing(B, olt_gpu, price['average'][t])),
                 fmt_batch(crossing(B, olt_net, price['average'][t]))] for t in ("onu", "user")])
    L += [""]

    curve = OltCurve(ref_rows, 1.0)
    idle_q = curve.pf1_net * pin + curve.dec1_net * gout
    busy_q = curve.pf_slope * pin + curve.dec_slope * gout
    adj = [r["marginal_J_per_query"] for r in ref_rows if r["batch"] >= 16]
    L += ["## 6. Marginal cost: what one more query adds", "",
          "A query that finds the OLT idle adds the energy above idle (net rates at batch 1). "
          "One that joins a running batch adds the slope of the batch's energy per step against "
          f"batch size (least squares over batches {B[0]}–{B[-1]}). Whole system under marginal "
          f"accounting: × {k_marg:.2f} (the idle-machines share left out).", ""]
    L += table(["", "J per prompt token (card)", "J per generated token (card)", "J/query, card",
                f"J/query, whole system × {k_marg:.2f}"],
               [["OLT idle (batch 1)", f"{curve.pf1_net:.4f}", f"{curve.dec1_net:.3f}", f"{idle_q:.1f}",
                 f"{idle_q * k_marg:.1f}"],
                ["OLT busy (slope)", f"{curve.pf_slope:.4f}", f"{curve.dec_slope:.4f}", f"{busy_q:.1f}",
                 f"{busy_q * k_marg:.1f}"]])
    L += ["", f"For comparison, the slope measured between adjacent batches from 16 up (table 1, "
              f"{ref_rows[0]['input_tokens'] // ref_rows[0]['batch']} in / {ref_run['output_tokens_per_sequence']} out "
              f"tokens): {', '.join(f'{a:.1f}' for a in adj)} J at the card.", ""]

    L += ["## 7. Answers: every tier on all GSM8K test questions", "",
          "Confidence = exp(mean token logprob), RecServe's. Welch t: how clearly confidence is higher on "
          "correct than on wrong answers, for exp(mean) and exp(min) of the token logprobs.", ""]
    rows = []
    for t in TIERS:
        rs = recs[t]
        ok, bad = [r for r in rs if r["correct"]], [r for r in rs if not r["correct"]]
        trunc = sum(r["trunc"] for r in rs)
        rows.append([t, models[t].split("/")[-1], len(rs), f"{len(ok) / len(rs):.3f}",
                     f"{st.mean(r['cmean'] for r in rs):.3f}", f"{tok[t][0]:.1f}", f"{tok[t][1]:.1f}",
                     f"{trunc} ({trunc / len(rs):.1%})",
                     f"{welch_t([r['cmean'] for r in ok], [r['cmean'] for r in bad]):+.2f}",
                     f"{welch_t([r['cmin'] for r in ok], [r['cmin'] for r in bad]):+.2f}"])
    L += table(["Tier", "Model", "n", "Accuracy", "Mean confidence", "Prompt tokens", "Generated tokens",
                "Hit 512-token limit", "Welch t, exp(mean)", "Welch t, exp(min)"], rows)
    L += [""]

    OUT.write_text("\n".join(L))
    print("\n".join(L))
    print(f"wrote {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
