#!/usr/bin/env python3
"""Tables for the trace-driven baseline (run_trace_baseline.sh, energy_tests.md §8.5).

For every scenario (trace, accounting, ONU cost, households x queries per day) and
OLT peak load, J per query at 0.70 and 0.80 accuracy from each policy's frontier,
mean over seeds, and four savings computed per seed (mean, and min..max over seeds):

    fixed -> schedule   what a time-of-day schedule saves over the better fixed chain
    fixed -> piggyback  what piggyback saves over the better fixed chain
    schedule -> pb      what piggyback saves over the schedule (the live signal's worth)
    schedule -> oracle  the most any live signal could save over the schedule

The fixed chains are three-tier RecServe (stepwise) and the ONU dropped (skip_onu).

    python src/scripts/summarize_trace_runs.py      # writes results/energy_tests/trace/SUMMARY.md
"""
from __future__ import annotations

import collections
import json
import statistics as st
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))       # implementation/src
from energy.three_tier import RESULTS  # noqa: E402

DIR = RESULTS / "trace"
TARGETS = ("0.70", "0.80")


def saving(new, ref):
    return None if new is None or ref is None else 1 - new / ref


def fmt(xs, pct=True):
    xs = [x for x in xs if x is not None]
    if not xs:
        return "-"
    m = st.mean(xs)
    if not pct:
        return f"{m:.1f}"
    return f"{m:+.1%} ({min(xs):+.0%}..{max(xs):+.0%})" if len(xs) > 1 else f"{m:+.1%}"


def main() -> int:
    runs = collections.defaultdict(list)
    for p in sorted(DIR.glob("sim_trace_*.json")):
        d = json.load(open(p))
        a = d["args"]
        key = (a["load_trace"], a["accounting"], float(a["onu_scale"]), int(a["households"]), int(a["per_day"]))
        runs[key].append(d)
    if not runs:
        print(f"no runs in {DIR}", file=sys.stderr)
        return 1

    lines = ["# Trace-driven baseline — summary", "",
             "Generated by `src/scripts/summarize_trace_runs.py`. J per query at the target accuracy "
             "(each policy's frontier), mean over seeds; savings per seed, mean (min..max). "
             "Positive = the second policy uses less energy.", ""]
    for key in sorted(runs, key=lambda k: (k[0] != "conversation", k[1], -k[2], k[3])):
        trace, acct, onu, hh, pd = key
        ds = runs[key]
        fixed = ds[0]["fixed_J_per_query"]
        lines += [f"## {trace}, {acct} accounting, ONU {fixed['onu']:.0f} J, {hh} household(s) x {pd}/day "
                  f"({len(ds)} seeds)", "",
                  "| load | acc | stepwise | skip_onu | schedule | piggyback | oracle | fixed → schedule "
                  "| fixed → piggyback | schedule → piggyback | schedule → oracle |",
                  "|---|---|---|---|---|---|---|---|---|---|---|"]
        peaks = sorted({f["peak_load"] for f in ds[0]["frontiers"]})
        for peak in peaks:
            for t in TARGETS:
                per_seed = []
                for d in ds:
                    J = {f["policy"]: f["J_at_accuracy"][t] for f in d["frontiers"] if f["peak_load"] == peak}
                    fx = [J[p] for p in ("stepwise", "skip_onu") if J.get(p) is not None]
                    best = min(fx) if fx else None
                    per_seed.append((J, saving(J["schedule"], best), saving(J["piggyback"], best),
                                     saving(J["piggyback"], J["schedule"]), saving(J["oracle"], J["schedule"])))
                col = lambda p: fmt([s[0].get(p) for s in per_seed], pct=False)
                lines.append(f"| {peak:g} | {t} | {col('stepwise')} | {col('skip_onu')} | {col('schedule')} | "
                             f"{col('piggyback')} | {col('oracle')} | " +
                             " | ".join(fmt([s[k] for s in per_seed]) for k in (1, 2, 3, 4)) + " |")
        lines.append("")
    out = DIR / "SUMMARY.md"
    out.write_text("\n".join(lines))
    print("\n".join(lines))
    print(f"wrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
