#!/usr/bin/env python3
"""Tables for the case study (run_study.sh, energy_tests.md §8.6).

Reads results/energy_tests/study/study_<scenario>_seed<n>.json and writes
results/energy_tests/study/SUMMARY.md:

  1. Headline, on the main settings (config/study.yaml), at 0.80 accuracy, for
     predictable traffic (surge factor 1) and each level of surprise:
       a. what the timetable and the dynamic policy save over RecServe;
       b. what the dynamic policy saves over the timetable, beside the most any
          live signal could (the oracle), and what piggyback on answers alone does.
  2. One full table per scenario: every policy's J per query at 0.70 and 0.80 and
     the comparisons, mean over seeds with the range across them.

A dagger marks a load at which the OLT's load exceeded the measured batch range
(64 in service) for more than 1% of arrivals: those rows are indicative only.

    python src/scripts/summarize_study.py
"""
from __future__ import annotations

import collections
import json
import statistics as st
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))       # implementation/src
from energy.three_tier import RESULTS  # noqa: E402

DIR = RESULTS / "study"
NAMES = {"stepwise": "RecServe", "skip_onu": "RecServe w/o ONU", "schedule": "timetable",
         "broadcast": "dynamic", "piggyback": "piggyback", "oracle": "oracle"}
COMPARE = [("schedule", "stepwise"), ("broadcast", "stepwise"), ("broadcast", "schedule"),
           ("piggyback", "schedule"), ("oracle", "schedule")]
MAIN = ["main_surge1", "main_surge1.5", "main_surge2", "main_surge3", "main_surge5"]
ORDER = MAIN + ["alltraffic"] + [f"{s}_surge{f}" for s in ("average", "onu0.2", "hh1x2000", "hh10x200",
                                                            "hh100x20", "perhousehold") for f in (1, 3)]


def saving(new, ref):
    return None if new is None or ref is None else 1 - new / ref


def pct(xs, spread=True):
    xs = [x for x in xs if x is not None]
    if not xs:
        return "-"
    m = st.mean(xs)
    return f"{m:+.1%} ({min(xs):+.0%}..{max(xs):+.0%})" if spread and len(xs) > 1 else f"{m:+.1%}"


def joules(xs):
    xs = [x for x in xs if x is not None]
    return f"{st.mean(xs):.1f}" if xs else "-"


def at(d, peak, acc):
    return {f["policy"]: f["J_at_accuracy"][acc] for f in d["frontiers"] if f["peak_load"] == peak}


def dagger(ds, peak):
    return any(c["peak_load"] == peak and c.get("share_arrivals_over_64", 0) > 0.01
               for d in ds for c in d["configs"])


def describe(d):
    a = d["args"]
    surge = float(a["surge_factor"])
    traffic = (f"{a['load_trace']} traffic" + (" as recorded" if surge == 1 else f", surges and dips x{surge:g}"))
    return (f"{traffic}; {a['accounting']} accounting; ONU {d['fixed_J_per_query']['onu']:.0f} J; "
            f"{a['households']} household(s) x {a['per_day']}/day; question statistics "
            f"{'shared' if a['shared_stats'] == 'True' else 'per household'}")


def main() -> int:
    runs = collections.defaultdict(list)
    for p in sorted(DIR.glob("study_*_seed*.json")):
        runs[p.stem[len("study_"):].rsplit("_seed", 1)[0]].append(json.load(open(p)))
    if not runs:
        print(f"no runs in {DIR}", file=sys.stderr)
        return 1
    peaks = sorted({f["peak_load"] for d in next(iter(runs.values())) for f in d["frontiers"]})
    L = ["# Case study — summary", "",
         "Generated by `src/scripts/summarize_study.py` from `run_study.sh`. J per query at the target "
         "accuracy (each policy's frontier), mean over seeds; savings per seed, mean (min..max). Positive = "
         "the first policy uses less energy. † = the OLT's load exceeded the measured batch range (64 in "
         "service) for over 1% of arrivals: indicative only.", ""]

    main_rows = [s for s in MAIN if s in runs]
    if main_rows:
        L += [f"## Headline — {describe(runs[main_rows[0]][0]).split('; ', 1)[1]}, 0.80 accuracy", "",
              "### Saving over RecServe: timetable / dynamic", "",
              "| traffic | " + " | ".join(f"load {p:g}" for p in peaks) + " |",
              "|---|" + "---|" * len(peaks)]
        for s in main_rows:
            ds, f = runs[s], float(runs[s][0]["args"]["surge_factor"])
            cells = []
            for p in peaks:
                J = [at(d, p, "0.80") for d in ds]
                cells.append(f"{pct([saving(j['schedule'], j['stepwise']) for j in J], False)} / "
                             f"{pct([saving(j['broadcast'], j['stepwise']) for j in J], False)}"
                             + (" †" if dagger(ds, p) else ""))
            L.append(f"| {'predictable' if f == 1 else f'surprises x{f:g}'} | " + " | ".join(cells) + " |")
        L += ["", "### Saving over the timetable: dynamic (oracle ceiling) · piggyback on answers only", "",
              "| traffic | " + " | ".join(f"load {p:g}" for p in peaks) + " |",
              "|---|" + "---|" * len(peaks)]
        for s in main_rows:
            ds, f = runs[s], float(runs[s][0]["args"]["surge_factor"])
            cells = []
            for p in peaks:
                J = [at(d, p, "0.80") for d in ds]
                cells.append(f"{pct([saving(j['broadcast'], j['schedule']) for j in J], False)} "
                             f"({pct([saving(j['oracle'], j['schedule']) for j in J], False)}) · "
                             f"{pct([saving(j['piggyback'], j['schedule']) for j in J], False)}"
                             + (" †" if dagger(ds, p) else ""))
            L.append(f"| {'predictable' if f == 1 else f'surprises x{f:g}'} | " + " | ".join(cells) + " |")
        L.append("")

    for s in [s for s in ORDER if s in runs] + sorted(set(runs) - set(ORDER)):
        ds = runs[s]
        pols = [p for p in NAMES if p in ds[0]["args"]["policies"].split(",")]
        L += [f"## `{s}` — {describe(ds[0])} ({len(ds)} seeds)", "",
              "| load | acc | " + " | ".join(NAMES[p] for p in pols) + " | "
              + " | ".join(f"{NAMES[a]} vs {NAMES[b]}" for a, b in COMPARE) + " |",
              "|---|---|" + "---|" * (len(pols) + len(COMPARE))]
        for p in peaks:
            for acc in ("0.70", "0.80"):
                J = [at(d, p, acc) for d in ds]
                L.append(f"| {p:g}{' †' if dagger(ds, p) else ''} | {acc} | "
                         + " | ".join(joules([j.get(q) for j in J]) for q in pols) + " | "
                         + " | ".join(pct([saving(j.get(a), j.get(b)) for j in J]) for a, b in COMPARE) + " |")
        L.append("")

    out = DIR / "SUMMARY.md"
    out.write_text("\n".join(L))
    print("\n".join(L))
    print(f"wrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
